version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:123456@database:3306/transfer_money
      - API_PORT=3001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=transfer_money
  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: "always"
