version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    networks:
      - internal_network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:123456@database:3306/transfer_money
      - API_PORT=3001
      - JWT_KEY=d21@sd*2sd
    networks:
      - internal_network
    restart: always
  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: "always"
    networks:
      - internal_network

networks:
  internal_network:
